### ISSUE TITLE
Test system information

### ISSUE THREAD

**Issue by prince-chrismc** [guteksan/REST-CPP-benchmark#2]
Firstly, WOW! Thank you for doing this!

One detail you skipped in your summary, which is absolutely key in evaluating the results, in the test system configuration. Number of cores is helpful, but some libraries are OS specific. If you could provide a detailed box about the system that would be hugely appreciated.

> The followings are some snapshots from the results of MacBook Pro (Retina, 15-inch, Mid 2015, Corei7-4980HQ@2.80GHz) with clang 7.0 64-bit.

> The tests were ran on a Dell R710, 2x X5660@2.80 with 64Gb RAM on an Ubuntu Server 16.04.3.

Just a quick sentence for us to better understand you test vector =)

Thanks again for these results!

**Comment by guteksan** [comment]
Hi @prince-chrismc 
Thanks for your interest and valid point. I have updated the benchmark with system information.

**Comment by prince-chrismc** [comment]
Wonderful! Exactly what I needed!
